### ISSUE TITLE
Compiled files missing in release

### ISSUE THREAD

**Issue by sschreier** [runelaenen/shopware6-advanced-banners#12]
You have forgot the file **rune-laenen-advanced-banners.js** under **Resources/public/administration/js/** , so the plugin only occurs in the administration when you rebuild the administration via cli, that you shouldn't do in the production system.

**Comment by runelaenen** [comment]
Possible solution in https://github.com/runelaenen/shopware6-two-factor-auth/issues/29
I'll take a look at this soon to implement the correct build CI.

**Comment by sschreier** [comment]
When I download the zip at master- or v1.0.2.1 - branch the file is still missing.

**Comment by runelaenen** [comment]
Please don't download zips from branches. These are only for development. The release zip should have all the files now: https://github.com/runelaenen/shopware6-advanced-banners/releases/tag/v1.0.2.1
