### ISSUE TITLE
Missing German translations

### ISSUE THREAD

**Issue by sschreier** [runelaenen/shopware6-advanced-banners#13]
Especially for german users there is no text snippet file (**de_DE.json** under https://github.com/runelaenen/shopware6-advanced-banners/tree/master/src/Resources/app/administration/src/module/rl-advanced-banners/snippet ), so when you switch the language to German you see the technical snippet namens.

**Comment by runelaenen** [comment]
I don't speak German so someone else will have to do these translations. For first timers: I've written a small get-started guide in a comment on the same issue for another plugin: https://github.com/runelaenen/shopware6-two-factor-auth/issues/2

**Comment by sschreier** [comment]
> I don't speak German so someone else will have to do these translations. For first timers: I've written a small get-started guide in a comment on the same issue for another plugin: [runelaenen/shopware6-two-factor-auth#2](https://github.com/runelaenen/shopware6-two-factor-auth/issues/2)

No problem, I have done a pull request: https://github.com/runelaenen/shopware6-advanced-banners/pull/16/files

**Comment by runelaenen** [comment]
> > I don't speak German so someone else will have to do these translations. For first timers: I've written a small get-started guide in a comment on the same issue for another plugin: [runelaenen/shopware6-two-factor-auth#2](https://github.com/runelaenen/shopware6-two-factor-auth/issues/2)
> 
> No problem, I have done a pull request: https://github.com/runelaenen/shopware6-advanced-banners/pull/16/files

Awesome! Thank you very much!
