### ISSUE TITLE
Multi-language not working

### ISSUE THREAD

**Issue by MelvinAchterhuis** [runelaenen/shopware6-advanced-banners#18]
**Example:**

Make banner in English with text and save. Change language to Dutch and translate text.

**Expected result:**

When changing language on the storefront the text changes according to the selected language, when no translation is provided inherit text from default language.

**Actual result:**

The Dutch text gets loaded both on English and Dutch storefront

**Comment by runelaenen** [comment]
This issue has been fixed in the master branch and will be available in 2.0.0 release.
