### ISSUE TITLE
Delete blocks when uninstalling plugin

### ISSUE THREAD

**Issue by MelvinAchterhuis** [runelaenen/shopware6-advanced-banners#19]
When uninstalling the plugin while CMS pages have an Advanced Banner assigned the CMS breaks

Steps to reproduce:

- Install plugin
- Create banner
- Assign banner to CMS page
- Uninstall plugin

**Comment by runelaenen** [comment]
This issue has been fixed in the master branch and will be available in 2.0.0 release.
