### ISSUE TITLE
6.4 compatibility

### ISSUE THREAD

**Issue by viosysadmin** [runelaenen/shopware6-advanced-banners#26]
Hi,

do you have any plans to make your plugin shopware 6.4 compatible?
I.e. i've got currently an exception when building the admistration:

ModuleNotFoundError: Module not found: Error: Can't resolve 'src/core/data-new/criteria.data' in '[...]vendor/runelaenen/shopware6-advanced-banners/src/Resources/app/administration/src/module/sw-cms/elements/rl-advanced-banner-slider/config'

**Comment by runelaenen** [comment]
I have started working on a new version that is completely compatible with 6.4.
However, I am currently moving to a new house and renovating it, so I don't have a lot of free time to work on my plugins.

You are free to submit a PR with fixes, I'm happy to review & merge it ;)

**Comment by FalkoHilbert** [comment]
Closed by pr #27
