### ISSUE TITLE
Next slide shows up for a second on page reload

### ISSUE THREAD

**Issue by Patric96** [runelaenen/shopware6-advanced-banners#29]
On reload the second slide appears briefly. Is this a bug?
You can see the issue here: https://elastic-khayyam.212-34-165-121.plesk.page/

Thanks for help!

**Comment by runelaenen** [comment]
Hi @Patric96 

Thank you for your feedback.

This is a bug in the slider implementation used by Shopware. (you will see the same thing happening with the sliders from core cms elements)
This issue is thus out of scope for this project.
